### ISSUE TITLE
Examples - React Hello won't install

### ISSUE THREAD

**Issue by timarney** [ericelliott/tdd-es6-react#1]
I've tried a few times to install the react-hello example but I haven't been successful.  NPM runs and runs until I cancel it.

tdd-es6-react/examples/react-hello

Can you confirm the app installs etc... I'm running the latest version of Node.  I was able to install and run the other examples.

**Comment by ericelliott** [comment]
What version of npm are you using?

``` sh
npm --version
```

**Comment by ericelliott** [comment]
I can confirm that it installs with npm version `2.14.2`.

**Comment by ericelliott** [comment]
Dug in a little -- it works with Node 0.12.5 & npm 2.11.2 but it does not work with Node 4.*

**Comment by ericelliott** [comment]
If you're interested in taking a crack at fixing for Node 4 and npm 3, I'm open to a pull request.

**Comment by timarney** [comment]
Okay thanks for taking a look.  I have npm 2.14.2 installed and running Node v4.  I'll dig into it further next week (hopefully).

**Comment by ericelliott** [comment]
I use `nvm` to easily switch Node versions. You may want to try it with a 0.12.x version. Definitely let me know if you have any luck with 4.x+

**Comment by timarney** [comment]
I believe the Node 4 issue is caused by jsdom (repo says "as of our 4.0.0 release, jsdom requires io.js or Node.js 4 or newer") 

I updated package.json to ->  "jsdom": "^6.5.1" and managed to get it to compile.  

With that updated all the test pass except 1... there's an issue with document.body being null (the iframe).

I'm not familiar with jsdom at this point so I wasn't able to fix that yet but, narrows it down.

**Comment by ericelliott** [comment]
Merged. However, it's clear that there are some 4.0 issues in some of the other modules we depend on for the tools.

This should be good to illustrate the points for this presentation, though. Thanks for looking into it!
